// Mocks generated by Mockito 5.4.6 from annotations
// in ecoride/test/core/providers/user_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ecoride/core/models/api_response.dart' as _i2;
import 'package:ecoride/core/models/user.dart' as _i5;
import 'package:ecoride/core/models/user_settings.dart' as _i6;
import 'package:ecoride/core/services/user_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i3.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponse<_i5.User>> getUserProfile(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [userId],
        ),
        returnValue: _i4.Future<_i2.ApiResponse<_i5.User>>.value(
            _FakeApiResponse_0<_i5.User>(
          this,
          Invocation.method(
            #getUserProfile,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<_i5.User>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.User>> updateUserProfile(
    String? userId,
    _i5.UpdateProfileRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [
            userId,
            request,
          ],
        ),
        returnValue: _i4.Future<_i2.ApiResponse<_i5.User>>.value(
            _FakeApiResponse_0<_i5.User>(
          this,
          Invocation.method(
            #updateUserProfile,
            [
              userId,
              request,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<_i5.User>>);

  @override
  _i4.Future<_i2.ApiResponse<_i6.UserSettings>> getUserSettings(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserSettings,
          [userId],
        ),
        returnValue: _i4.Future<_i2.ApiResponse<_i6.UserSettings>>.value(
            _FakeApiResponse_0<_i6.UserSettings>(
          this,
          Invocation.method(
            #getUserSettings,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<_i6.UserSettings>>);

  @override
  _i4.Future<_i2.ApiResponse<_i6.UserSettings>> updateUserSettings(
    String? userId,
    _i6.UserSettings? settings,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserSettings,
          [
            userId,
            settings,
          ],
        ),
        returnValue: _i4.Future<_i2.ApiResponse<_i6.UserSettings>>.value(
            _FakeApiResponse_0<_i6.UserSettings>(
          this,
          Invocation.method(
            #updateUserSettings,
            [
              userId,
              settings,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<_i6.UserSettings>>);
}
